#!/usr/bin/env python
import sys, os, re
from subprocess import check_output
# Collect the parameters
commit_msg_filepath = sys.argv[1]
# Figure out which branch we're on
#branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
#print "commit-msg: On branch '%s'" % branch

# Read commit message
with open(commit_msg_filepath, 'r') as f:
    content = f.read()

if not content.startswith("# "):
    print("commit-msg: ERROR! The commit message must start with  \"# \"")
    sys.exit(1)
if len(content) < 8:
    print("commit-msg: ERROR! The commit message is too short, required minimum 8 character!")
    sys.exit(1)

sys.exit(0)
