# This is a sample build configuration for C++ – Make.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: gcc:6.1

pipelines:
  default:
    - step:
        script:
          - echo 'Start pipeline'
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - gcc --version
          #  Install a CMake 3.0.2 version.
          #- apt-get update -qq
          #- apt-get install cmake -y
          #  Alternatively you could install a CMake 3.2.2 version through PPA repository.
          - apt-get update -qq
          - apt-get install software-properties-common -y
          # Add PPA repository.
          - echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/cmake.list
          - apt-get update -qq
          - apt-get install cmake -y --force-yes
          # Print the CMake version.
          - echo 'Start CMake'

          - cmake --version

          - cd $BITBUCKET_CLONE_DIR
          
          #- mkdir Out
          #- cd Out
          #- mkdir CMakeBuild
          #- cd CMakeBuild

          # Call the CMake.
          #- cmake ../..
          # Normally: "- cmake" is enough
          - cmake CC=gcc .
          # -D"CMAKE_MAKE_PROGRAM:FILEPATH=make.exe" -D"CMAKE_C_COMPILER:FILEPATH=gcc.exe" -D"CMAKE_CXX_COMPILER:FILEPATH=g++.exe" CC=gcc -G "MinGW Makefiles"

          # Build the project.
          - echo 'Start Make'
          - make
